### ISSUE TITLE
SEP V022: Inert DNA Spacer

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#103]
This SEP proposes to add a new glyph for inert DNA spacer sequences, generalizing on the concept of an insulator.

https://github.com/SynBioDex/SBOL-visual/blob/master/SEPs/SEP_V022.md

Note that this SEP also assumes a requested adjustment of the SO term will resolve, though this may take some time (see: https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/494)

**Comment by JS3xton** [comment]
The SEP looks good to me. Thanks @jakebeal!

**Comment by shyambhakta** [comment]
If you want an example in the SEP, here's my recreation of the yeast intergenic insulators from [yeast Cello paper, fig 3/4](https://www.nature.com/articles/s41564-020-0757-2):
![image](https://user-images.githubusercontent.com/5035245/95014377-08168580-060c-11eb-9e63-e6e86c2ddfe6.png)
Top: personal PPT glyphs; Bottom: published glyphs. 180° rotated chromsomal context glyph.

(I find it funny that their figures use the newer chromosomal context glyph, but still uses the old RNA cleavage site glyph for ribozymes.)

**Comment by jakebeal** [comment]
@shyambhakta This is excellent; can you share an editable vector version (SVG or PPTX preferred)

**Comment by shyambhakta** [comment]
Here it is. 
[yeast intergenic insulator.pptx](https://github.com/SynBioDex/SBOL-visual/files/5323185/yeast.intergenic.insulator.pptx)

Unrelated: as I've been making quick diagrams in PowerPoint over the years, I've accrued a set of glyphs like those in the top diagram that are sort of standardized in terms of recreation in PowerPoint / conversion and adjustment into black vector Shapes (as opposed to Graphics) with 2 pt line width, square caps and miter joints, adjusted in size to my liking. Most notably, a CDS glyph made using the PowerPoint arrow (widened to the preferred pentagon) doesn't distort the pointed angle when lengthening the glyph.
Compare with the glyphs as taken directly from the current SVG glyph folder, bottom diagram. (except for the spacer glyph. And the terminator glyph still only has the bounding box version in the folder, though easy to delete. Needs to be fixed.)

Minor note: the current chromosomal context glyph looks better rotated, making a smooth joint with the backbone. The angled joint isn't as aesthetically-pleasing, as seen here in the yeast Cello paper: 
![image](https://user-images.githubusercontent.com/5035245/95014543-39dc1c00-060d-11eb-8803-f342f2b9c0fa.png)

**Comment by jakebeal** [comment]
Thank you; I've added the figure to both the SEP and the proposed spec diff.

As for improved glyphs: do please make a pull request to improve the current glyphs if you've got improved versions, like the rotated chromosome inserts!  These count as "font-level" tweaks, and the original versions are by no means perfect.

**Comment by shyambhakta** [comment]
Cool, I'll give it a try.
One tweak: should be "ribozyme" not "protease" in that example description.

**Comment by jakebeal** [comment]
Thanks, fixed.

**Comment by jakebeal** [comment]
Closing as accepted and incorporated.
