### ISSUE TITLE
Migrate all ontology resources and website to community locations

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#107]
Currently some of the key resources for the ontology are hosted outside of @goksel's personal github account rather than the SBOL community organization or website. For maintainability, it would be good to migrate them.

The resources that need to be migrated are:
 - Code for maintaining the ontology: https://github.com/dissys/sbol-visual-ontology
 - Ontology website: https://dissys.github.io/sbol-visual-ontology/

The READMEs in this repository should also be reflected to document all of these things as well.

**Comment by goksel** [comment]
@jakebeal The SynBioDex/sbol-visual-ontology now includes the latest changes. The README file has been updated accordingly. Could the editors update the SBOL website links please?
https://github.com/SynBioDex/sbol-visual-ontology
https://synbiodex.github.io/sbol-visual-ontology/
Please close the issue, after you review this.

**Comment by jakebeal** [comment]
@goksel Have the editors made the updates that you need, or can you open that as a separate issue linked to this one?  If they're done or you open a separate issue, then we can close this one.
