### ISSUE TITLE
Interaction nodes Process and Association are the same 

### ISSUE THREAD

**Issue by Gonza10V** [SynBioDex/SBOL-visual#111]
Reviewing the used Process interaction node I noticed that its [prototypical example](https://github.com/SynBioDex/SBOL-visual/tree/master/Glyphs/InteractionNodes/process#prototypical-example)  is the same in Association [prototypical example](https://github.com/SynBioDex/SBOL-visual/tree/master/Glyphs/InteractionNodes/association#prototypical-example). This can be confusing for more people should be avoided.

**Comment by jakebeal** [comment]
Agreed.  I believe this can be fixed without an SEP, since it's not changing any definitions, just making a nicer example.

**Comment by jakebeal** [comment]
Anybody got a good example to add?  I'm thinking some sort of enzymatically catalyzed transformation might be good.

**Comment by Gonza10V** [comment]
My first candidate of enzymatic catalysis was LuxI, because is well known in SynBio, but could be a bit complicated https://www.uniprot.org/uniprot/P12747 
so to keep it simple and of general known I think in an enzymatic catalysis from Krebs cycle could be fine. For example 
Incomming[ smallmolecule(Citrate), macromolecule(Aconitase)-Process- Outgoing[ smallmolecule(cis-Aconitate)].

**Comment by jakebeal** [comment]
Sounds great! Do you want to try putting together the diagram?   The Aconitase should probably use the control arrowhead rather than reactant, however, to indicate it role as catalyst rather than reactant.

**Comment by Gonza10V** [comment]
I put the proposed example together adding the control arrowhead to Aconitase.

![image](https://user-images.githubusercontent.com/35148159/98063144-1d124e80-1e2e-11eb-86fc-7573db551afc.png)

**Comment by jakebeal** [comment]
@Gonza10V This looks great!  Can you set up a pull request for incorporating this modification in?  Alternately, if you are uncomfortable doing that, you could send me the vector source for the PNG and I can make the modification.

**Comment by Gonza10V** [comment]
@jakebeal I prefer to do it myself to gain experience. I would appreciate some guides about. I should upload the svg and png to process folder on InteractionNodes using what names something like process-example.png and process-example.svg, should I also add the png example to the readme, if so what size should I use?

**Comment by jakebeal** [comment]
@Gonza10V That's correct. We want the SVG to be editable, and the PNG for the README, since the SVG won't show up there. For size, just make it show up relatively at scale in the README.  Here is a good example of a glyph with graphical examples: https://github.com/SynBioDex/SBOL-visual/tree/master/Glyphs/chromosomal-locus

You'll want to do this in a fork and then submit a pull request.
