### ISSUE TITLE
Summary SEP catalog

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#114]
Automate generation of an SEP catalog collection in this repository, as has been done for the SBOL Data SEPs.

**Comment by jamesscottbrown** [comment]
To ensure that glyphs are listed in the correct place, I need to add a list of glyphs categorised by type (`FunctionalComponent`, `Species`, `Interaction`, `InteractionNode`).

To avoid duplication (ad the possibility of accidental divergence between the glyphs included in the spec and in the summary), I'll add this as a JSON file, and replace the shell scripts in `specification/glyphscripts.sh` with a single python script that reads the same file.

**Comment by jakebeal** [comment]
@jamesscottbrown You should be able to get this information out of the ontology, which now has those four categories, given the resolution of #96

**Comment by jamesscottbrown** [comment]
In [`interactionnodeglyphs.tex`](https://github.com/SynBioDex/SBOL-visual/blob/master/specification/glyphscript/interactionnodeglyphs.tex) the  `\twotwozeronopage` macro is used once, and wraps all of the included PDFs; in [`glyphs.tex`](https://github.com/SynBioDex/SBOL-visual/blob/master/specification/glyphscript/glyphs.tex) some PDFs are wrapped in `\twoonezeronopage`, some in `\twotwozeronopage`, and some in neither.

These inconsistencies currently don't occur in the automatically generated output of the shell scripts - do you know whether they are necessary manual tweaks, or just historical artefacts?

**Comment by jakebeal** [comment]
The annotations are currently added manually. Since the BioPAX to SBO change in 2.2 affected all of the interaction and interaction node glyphs, it's not surprising that they all ended up wrapped in a single changebar note. Amongst the sequence feature glyphs, on the other hand, only a handful have been affected at each version, and so only some are wrapped while others are not.
