### ISSUE TITLE
Website should implicitly link to latest release

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#120]
The website currently has to be manually updated for each release.  Once we generate release artifacts automatically (#119), the website can instead point all of its links just to "latest release" URLs in GitHub, such that when we make a new release the website will be mostly automatically updated. 

We can also stop linking old release material on the website, and just give an "old releases here" pointer to the release collection on GitHub.

**Comment by hasanbaig** [comment]
Agreed! Shouldn't this issue be a part of [SbolStandardWebsite](https://github.com/SynBioDex/SbolStandardWebsite) repository?

**Comment by jakebeal** [comment]
I filed it here because it's dependent on #119; feel free to mirror it over there if you wish.

**Comment by jakebeal** [comment]
Migrated issue to website issue tracker.
