### ISSUE TITLE
Smarter automation on glyph script updates

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#125]
The scripts in specification/glyphscripts are rather dumb, and will generate complete new copies of every glyph page for the specification, whether or not it needs to be updated. The PDFs are not identical, however, due to date-stamping, which messes up the git diffs and can obscure the actual update.

Can we make these scripts smarter so that they actually update only those things that need to be updated? If we do that, then we could also have them automated on pull requests rather than having them have to be run by hand.

**Comment by jamesscottbrown** [comment]
This is hopefully addressed by `scripts/rebuild_glyphs.py`.
