### ISSUE TITLE
SEP V008: Functional Component Glyphs

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#13]
Like SBOL 2, SBOL Visual 2 needs to express not just the structure of nucleic acids but also the functional relationships between nucleic acid regions and other species in a biological system. The functional component glyphs in this proposal come from two sources:

1. SBOL has committed to compatibility with SBGN, so glyphs align with the categories in SBGN-AF and every glyph includes the corresponding SBGN glyph as an alternative. 
2. A number of possible glyphs intended to be more "intuitive" for synthetic biologists have also been proposed.

Note that not all SBGN glyphs are being imported; we just commit that where an equivalence exists that the SBGN representation should be allowed.

Please see the full proposal at: https://github.com/SynBioDex/SBOLv-realizations/blob/develop/SEPs/SEP_V008.md

**Comment by cjmyers** [comment]
Types are a required field for ComponentDefinitions, so I don't think we will have Unspecified, at least not for valid SBOL.  Therefore, I would prefer to use the ellipse for No Assigned Glyph in this case.  This is consistent with SBGN usage, I believe.

As for the others, I would like to see the SBGN glyph be at least an alternate for compatibility reasons.  No strong opinions though on which should be the required.  Perhaps, single wiggle line for RNA and double wiggle line for DNA makes some physical sense.  Also, think the complex which is multiple overlapping glyphs is good.

**Comment by jakebeal** [comment]
Hi, Chris: while a type is required, there is no requirement that the type be BioPAX.  Thus, I think it's still quite possible to both end up with things defaulting to PhysicalEntity, and also have entities that want to be put into new categories that don't yet have glyphs.  Does that not argue for having the same distinction between Unspecified and No Glyph Assigned?

**Comment by cjmyers** [comment]
Not sure exactly what you mean.  If someone wants to create an object that does not map to a BioPax type then they will need to provide a term from a different ontology to do this.  This would be, in my opinion, the No Glyph Assigned case.  

Since a type is required, the Unspecified case would need to be there is a type but it is not really specifying the objects molecular type.  For example, we allow "circular" and "double stranded" in the list of types.  Therefore, in order to distinguish between No Glyph Assigned and Unspecified, a tool would need to be able to interpret "is this type specifying the molecular structure?".  I don't think this is possible, so it seems to me like these two cases fold onto each other assuming we have valid SBOL file.

Granted, the "Unspecified" could show up for invalid SBOL, in which case a ? glyph could make sense.

**Comment by jakebeal** [comment]
So do you strongly believe there is no need for "Unspecified"? I would prefer to keep the constructs parallel between functional and structural components, and would also prefer to not find ourselves revisiting this issue after discovering there is indeed a difference after all.

**Comment by cjmyers** [comment]
We can keep unspecified as ? character recommended.  I would just suggest that we allow ellipse to be an alternative for No Glyph Assigned rather than unspecified, since that should be rare and only for invalid SBOL.

**Comment by jakebeal** [comment]
~~I'm OK with moving it, and will do so.~~  I changed my mind, due to the extreme similarity of "ellipse" and "stadium."  Frankly, I would prefer to never see "ellipse" in a diagram, since it's too similar to the Small Molecule "stadium." We are, however, often going to see an ellipse when somebody means stadium, due to sloppiness, sketching, or the fact that "circle" matches both. 

Due to this potential for confusion, I think that it is important that the "ellipse" glyph be assigned to semantics that contains "stadium."  This is true for Unspecified (BioPAX PhysicalEntity), but is *not* true for No Glyph Assigned, which is specifically defined to be disjoint from Small Molecule.

On a less controversial note, I also added the "make up your own glyph" language from SEP V006.

**Comment by jakebeal** [comment]
My preferences:
- We should allow all SBGN alternatives, even though many are problematically similar, in order to maintain compatibility. 
- For recommended symbols:
  - Complex: I like the compositing version as being both intuitive and expressive.
  - ssNA: the "wiggle" already appears frequently in literature.
  - dsNA: I like the double helix: it and double-wiggle are natural compositions of ssNA wiggles, and the double-helix is both more physical and can't be confused with two ssNAs.
  - Macromolecule: I like our "budding blob", which is a simplified version of the blobby protein shapes that appear in the literature.
  - Small Molecule: the SBGN version is quite close to typical current practice in the literature, which tends to use circle, ellipse, or stadium. 
  - No Glyph Assigned, Unspecified: I like having these being parallel to the structural glyphs.

**Comment by sbhatia-catalog** [comment]
I think there can be an Unspecified case where, like abstract designs, the full details haven't been specified. It doesn't need to do any molecular structure etc. I propose to keep Unspec in each layer for this use case.

**Comment by swapnilb** [comment]
I think the Unspecified use case is important and applies here too. It refers to the case where the author has not decided on all the details of the design, including type. For example, a circuit designer hasn't decided how X will be regulated by Y, but wants to show that aspect. So I think Unspecified Type + Object should be possible.

**Comment by jakebeal** [comment]
@swapnilb It sounds like you and I are on the same page on this then.

**Comment by jakebeal** [comment]
As I am not hearing and objections to my suggested recommendations, I have updated the SEP accordingly.

**Comment by graik** [comment]
The macromolecule glyph looks like the informal but very commonly used symbol for "yeast cell". It's pretty much a standard among yeast biologists and also  beyond. 
More generally, perhaps its my structural biology upbringing, but I don't see how a big and a small circle should symbolize a macromolecule (such as, most commonly I suppose, a protein).

**Comment by graik** [comment]
The symbol suggested for small molecule (pill shape) is very commonly used to denote protein domains. See previous discussions about that topic. I propose to only allow a perfect circle for small molecules. A hexagon or octagon would be another alternative. Being small by definition, it should be fine if the label is generally given next to the symbol rather than within it.

**Comment by jakebeal** [comment]
@graik The macromolecule shape is intended to be a simplification of the wide range of "lumpy shape" images that appear for proteins in diagrams currently.

As for small molecule: we are committed to have the pill shape as at least one of the options, due to the need to maintain compatibility with SBGN -- this also precludes octagon.  Note, however, that "pill" is differentiated by context from protein domain diagrams, since there is no AA-backbone interacting with it.

**Comment by graik** [comment]
@jakebeal 
Circle or pill shape without base line = small molecule should indeed work. Perhaps you could make the circle with outside label the preferred symbol though. 

As to the macromolecule shape, I gathered that you had nothing particular in mind. It's just bad luck that yeast biologists have settled on this kind of symbol (or very similar) to represent a budding yeast cell which they then use synonymously for yeast in general. Intuitively, a small + large circle will either be interpreted as a ribosome or as a dividing cell.

Why not coming up with a truly irregular shape for the macromolecule?
![image](https://user-images.githubusercontent.com/1862877/31901194-696b38b4-b829-11e7-869f-7f83cf68515e.png)

**Comment by graik** [comment]
The following is what I use as "protein" symbol in my sample management: 
![image](https://user-images.githubusercontent.com/1862877/31902076-3ff47556-b82c-11e7-9d02-12acaac15e6c.png)

The helix inside could be replaced depending on macromolecule type. The top right and bottom left corner could be changed from rounded to sharp to create a unique outside shape that is still easy to draw.

**Comment by jakebeal** [comment]
I have a concern that your "protein" helix will be easily confused with the ssRNA wiggle.

I would be OK with potentially changing the macromolecule "irregular shape", but it needs to be easily drawn, replicated, and recognized---the "blob" you just drew is too hard on that, but some other image might work.

**Comment by jakebeal** [comment]
Accepted and integrated, and thus closed per SBOL procedure in updated SEP 001.
