### ISSUE TITLE
Minor tweaks on sampler

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#140]
I've noticed a couple of minor flaws on the autogenerated samplers:

1. Glyph name capitalization isn't preserved (e.g., `Polya`, `Cds`, `Dsna`). This information can be retrieved from the ontology.
2. Glyphs don't distinguish the recommended vs. alternate.

**Comment by jamesscottbrown** [comment]
The capitalization issue should be fixed: `scripts/glyph_list.json` now includes a `displayName` attributes containing the names exactly how they should appear on the sampler.

**Comment by jamesscottbrown** [comment]
The sampler now uses background color to distinguish recommended vs alternate glyphs.

(GitHub seems to do some caching of the PNG, but not PDF versions, so you might see older versions for a while)
