### ISSUE TITLE
SEP V010: Arrows

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOL-visual#17]
This SEP proposes to add arrow types to represent interactions.

Please see the full proposal at: https://github.com/SynBioDex/SBOLv-realizations/blob/develop/SEPs/SEP_V010.md

**Comment by jakebeal** [comment]
I have recommended adjustment of SEP V010 in the following ways:

- Consolidate all duplicate glyphs under their parent, Process
- Add examples
- Adjust format to match standard template

If you agree, please approve the following pull request: https://github.com/SynBioDex/SBOLv-realizations/pull/21

**Comment by jakebeal** [comment]
Accepted and integrated, and thus closed per SBOL procedure in updated SEP 001.
