### ISSUE TITLE
What are the glyph requirements for arrows?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#24]
Are there specific glyph requirements for interaction arrows, apart from those that are set out for other SBOL Visual glyphs?

I think that we may want to say the line can't have any specified shape.

**Comment by cjmyers** [comment]
Routing of arrows can be challenging, so I would guess that we want to be flexible.

**Comment by jakebeal** [comment]
In general, there's a whole lot of stuff that I think needs to be sorted out about arrows for SBOL Visual 2.1.  In addition to this (which I wrote as a reminder for when we're working on it), there is also reactions and multi-head and multi-tail arrows.

**Comment by cjmyers** [comment]
@jakebeal is this done in SBOL Visual 2.1?

**Comment by jakebeal** [comment]
Multi-head and multi-tail was resolved in SEP V013 (#47).
We have left "arrow" defined informally, and I think that's fine for now --- nobody seems to be proposing non-arrow-like arrows at present.
