### ISSUE TITLE
SBO terms for molecular species?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#26]
Per Nicolas Le Novere: SBGN associates each of its glyphs with an SBO term, and we should consider that change for SBOL Visual molecular species glyphs as well:

*Nicolas Le Novere wrote*
> SBO also provides terms for molecular species (all SBGN glyphs have to be associated with an SBO term). So we could also provide associated SBO terms in A.2
> 
> Complex:
> SBO:0000253 non-covalent complex
> 
> Single-stranded nucleic acid:
> Double-stranded nucleic acid:
> SBO:0000354 informational molecule segment
> 
> Note: I think there is a misunderstanding about the SBGN PD glyph "Nucleic Acid Feature". It is not meant to represent a molecule of DNA or RNA etc. This is done with a "Macromolecule" glyph carrying the appropriate "Unit of Information", set to DNA or RNA.  SBGN's "Nucleic Acid Feature" is used to represent the concept of the same name in SBOL, i.e. a portion of a macromolecule carrying a specific information, e.g. a gene, a coding sequence etc. It was necessary to distinguish in some models the reactions involving the whole nucleic acid (e.g. (de)polymerisation, degradation, translocation etc.) and reactions involving only part of it. Its shape is halfway from a unit of information (a rectangle) and a macromolecule (a round-corner rectangle)
> 
> Macromolecule:
> SBO:0000245 macromolecule
> 
> Small Molecule:
> SBO:0000247 simple chemical
> 
> Unspecified:
> SBO:0000285 material entity of unspecified nature

**Comment by cjmyers** [comment]
Duplicate #62?

**Comment by jakebeal** [comment]
Rather I would say that #62 is the implementation that will resolve this issue.

**Comment by jakebeal** [comment]
Closed by #66, implementing SEP V015 (#62)
