### ISSUE TITLE
Allow compositing a Molecular Species with a DNA backbone to show binding?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#27]
John Sexton observes that a molecular species in contact with a DNA backbone is often used to show binding into a complex in a diagram. We should consider whether SBOL Visual can be extended to allow this:

*John Sexton wrote:*
> In Section 6.3, the standard dictates that molecular species glyphs MUST NOT contact a nucleic acid backbone (page 14, line 3). I think this is unnecessarily restrictive; DNA binding domains of proteins often interact with DNA molecules but are still classified as molecular species. In the Tabor lab in particular, bacterial two-component systems are often illustrated as dimerized protein domains binding a DNA backbone (see [1], [2], [3], [4], [5]). These diagrams are currently not compliant with SBOL Visual 2.0 given the specification that molecular species MUST NOT touch a DNA backbone. I understand that edits to this document should not be substantive, but was this requirement included in a vote? I don't see it in SEP V008.

**Comment by jakebeal** [comment]
@JS3xton I'd like to try to resolve this: can you please draw some specific use cases diagrams for us to consider? I think that looking at a few diagrams will give a clear path forward.

**Comment by JS3xton** [comment]
Here are a few examples I could scrounge together quickly. They all seem to fall into the category of illustrating a protein, proteins, or protein-RNA complexes binding DNA.

### Transcriptional regulators:

- **Fig 5.22, panel 4** from [Ptashne's _A Genetic Switch_, 3rd Edition, 2004](https://www.amazon.com/Genetic-Switch-Third-Lambda-Revisited/dp/B001WAKRQE/) on phage lambda regulation:
    <img src="https://user-images.githubusercontent.com/2179825/38785508-916233c2-40e6-11e8-9490-afb5b27dd283.png" width="300" height="100" />
- **Fig 2** from [Schleif, _FEMS Microbiol Rev, 2010_](https://www.ncbi.nlm.nih.gov/pubmed/20491933) on arabinose operon regulation:
  <img src="https://user-images.githubusercontent.com/2179825/38785319-130e6038-40e4-11e8-80ab-1e3c824345fb.png" width="150" height="200" />
- Other systems for which I don't have primary literature diagrams at the moment: [_lac_ operon](https://en.wikipedia.org/wiki/Lac_operon), [_trp_ operon](https://en.wikipedia.org/wiki/Trp_operon).

### CRISPR and derivatives:
- **Fig 5A** from [Jinek _et al_, _Science_, 2012](https://www.ncbi.nlm.nih.gov/pubmed/22745249) introducing CRISPR:
  <img src="https://user-images.githubusercontent.com/2179825/38785796-067f3252-40e9-11e8-85c6-54f5aa656629.png" width="150" height="200" />
- **Fig 1B** and **Fig 3B** from [Qi _et al_, _Cell_, 2013](https://www.ncbi.nlm.nih.gov/pubmed/23452860) introducing CRISPR interference (CRISPRi):
  <img src="https://user-images.githubusercontent.com/2179825/38786205-07f64d7a-40ec-11e8-84bd-1b79f4c03393.png" width="200" height="150" /> <img src="https://user-images.githubusercontent.com/2179825/38786235-333b4d50-40ec-11e8-92a0-3b50fe233163.png" width="300" height="150" />
- **Fig 1A** from [Nielsen & Voigt, _Mol Syst Biol_, 2014](https://www.ncbi.nlm.nih.gov/pubmed/25422271) on CRISPRi logic circuits:
  <img src="https://user-images.githubusercontent.com/2179825/38786375-21a6e79c-40ed-11e8-8e74-97ca0ae26123.png" width="250" height="100" />

### Two-component system (TCS) biosensors:
- **Fig 1a** from [Levskaya _et al_, _Nature_, 2005](https://www.ncbi.nlm.nih.gov/pubmed/16306980) on engineering light sensors in _E. coli_:
  <img src="https://user-images.githubusercontent.com/2179825/38786702-2ebe8faa-40ef-11e8-8e29-eb6ec6bc6170.png" width="100" height="100" />
- **Fig 1D** from [Tabor _et al_, _Cell_, 2009](https://www.ncbi.nlm.nih.gov/pubmed/19563759) describing a bacterial edge detector:
  <img src="https://user-images.githubusercontent.com/2179825/38786842-1c649038-40f0-11e8-8196-4517e54b4f06.png" width="75" height="100" />
- **Fig 1a** and **Fig 1d** from [Schmidl _et al_, _ACS Synth Biol_, 2014](https://www.ncbi.nlm.nih.gov/pubmed/25250630):
  <img src="https://user-images.githubusercontent.com/2179825/38787026-48c6f110-40f1-11e8-94ce-8ac457a4a214.png" width="250" height="150" /><img src="https://user-images.githubusercontent.com/2179825/38787035-53db07b2-40f1-11e8-9b49-3c3ad2a1fc36.png" width="250" height="150" />
- Very similar diagrams can also be found in:
  - [Olson _et al_, _Nature Methods_, 2014](https://www.ncbi.nlm.nih.gov/pubmed/24608181)
  - [Ramakrishnan & Tabor, _ACS Synth Biol_, 2016](https://www.ncbi.nlm.nih.gov/pubmed/27120220)
  - [Daeffler _et al_, _Mol Syst Biol_, 2017](https://www.ncbi.nlm.nih.gov/pubmed/28373240)
  - [Olson, Tzouanas, Tabor, _Mol Syst Biol_, 2017](https://www.ncbi.nlm.nih.gov/pubmed/28438832)
  - [Ong, Olson, Tabor, _ACS Synth Biol_, 2018](https://www.ncbi.nlm.nih.gov/pubmed/29091422)
  - Landry _et al_, _Nature Comm_, 2018

**Comment by jakebeal** [comment]
So it looks like we would have no ambiguity there, at least, since the Macromolecule glyph is very different from all of the Sequence Feature glyphs.

Places where I do see potential ambiguity:
- Small Molecule vs. Origin of Replication - do small molecules ever bind directly?
- SBGN Unspecified Molecule vs. Origin of Replication - Unspecified is NOT RECOMMENDED anyway.
- SBGN Unspecified nucleic acid vs. SBGN Unspecified Sequence Feature - Unspecified is NOT RECOMMENDED anyway.

Regarding contact: if it's an RNA binding (e.g., siRNA), would that make an acceptable diagram? How would you draw that to look nice?

**Comment by jakebeal** [comment]
I have created an SEP to address this issue: #74
