### ISSUE TITLE
How can we represent non-ordered elements?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#30]
_From @jakebeal on August 1, 2016 0:43_

SBOL allows a ComponentDefinition to contain elements that are not ordered, e.g., sub-Components that must be contained but for which no linearization decision has yet been made.

Can we effectively represent this in SBOL visual diagrams?

_Copied from original issue: SynBioDex/SBOL-visual-deprecated#1_

**Comment by cjmyers** [comment]
There are several ways this can happen:
1) There are overlapping sequence annotations.
2) There are sequence constraints but they do not imply a total order.
3) There is no ordering information provided at all.

I think 2&3 can be solved by allowing software to provide an allowed order.  Though having some way to indicate this is not a mandatory order would be good.

Case 1 though does not seem to have any obvious solution.  It would definitely be good to have guidance on this.

**Comment by jakebeal** [comment]
Nobody seems to be particularly having trouble with sequences without any order, and overlapping is the focus of #57, so I am closing this issue. It can be reopened or recreated when we have motivation to address non-ordered sequences.
