### ISSUE TITLE
Non-ordered glyph priority

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#35]
SequenceOntology permits multiple parents for a term, which means that the ordering rules for glyph choice don't necessarily resolve which of two glyphs is preferred.

We should make an explicit recommendation for how to handle this.

**Comment by jakebeal** [comment]
I have added a patch for the specification in f2eb16d5 saying that if there's no order, either is OK:

> (if upward branching in the relevant ontology means two applicable glyphs do not have an ordered parent/child relation, either MAY be used).

If this is acceptable, I believe this may be treated as a simple clarification patch that does not require any vote. Editors, please review and either give me the go-ahead to merge or request otherwise.

**Comment by palchicz** [comment]
This looks good to me. My only comment would be to move the new sentence to after the following paragraph and accompanying image to keep the explanatory content close to the recommendation.

**Comment by jakebeal** [comment]
I have now tried changing the order, but found it made things less clear to me: I think it is important to keep all of the "rules" together as one batch, before we present the example.

Instead, I have clarified by changing the statement from a parenthetical note to a full sentence of specification. The final version is now in a pull request awaiting your review and approval: #42

**Comment by jakebeal** [comment]
Resolved with pull #42
