### ISSUE TITLE
Not all files present in zip files on sbolstandard.org

### ISSUE THREAD

**Issue by rgiessmann** [SynBioDex/SBOL-visual#39]
Dear all,

I tried to download the zipped collection of glyphs from http://sbolstandard.org/visual/glyphs/ -- however, in the file for nucleic acid glyphs in svg format (it's a hidden link to http://sbolstandard.org/download/nucleic-acid-glyphs-svg/?wpdmdl=2720 -- if the link doesn't work, please look for "Nucleic Acid Glyphs SVG, 40.49 KB, Download" on the web page) the promoter and terminator elements seem to be missing.

I am not sure if I contacted the right persons here, but I hope so. Otherwise, please let me know, so that I can write someone else...

Thanks in advance and all the best, 
   Robert

**Comment by shyambhakta** [comment]
I opened an [issue on this](https://github.com/SynBioDex/SBOL_website/issues/119) a few months back, but on the SBOL website issue tracker, figuring this is a website issue more than an SBOL Visual issue.
It's more than just those two glyphs.

**Comment by tramyn** [comment]
@rgiessmann, @shyambhakta: Apologies for the slow response and thank you both for reporting this issue. We have updated the link to retrieve the necessary nucleic acid SVG glyphs. If you are both satisfied with the changes made, feel free to close this issue. If not, please let us know and we will continue working on this. Thanks.

**Comment by shyambhakta** [comment]
Minor issue: the specific recombination site glyph isn't sized correctly.
Beyond that, great.

**Comment by tramyn** [comment]
@shyambhakta Did you want the shape to be longer? If so, I've updated that change.

**Comment by jakebeal** [comment]
Has this been resolved at this point? Can the issue be closed?

**Comment by rgiessmann** [comment]
Yes, issue resolved, thank you very much for your efforts!
