### ISSUE TITLE
SEP V001: Bounding box, interior, backbone alignment, and relative scale

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#4]
# SEP V001: Bounding box, interior, backbone alignment, and relative scale

| SEP | <leave empty> |
| --- | --- |
| **Authors** | Jacob Beal (jakebeal@ieee.org) |
| **Editor** | <leave empty> |
| **Type** | Specification |
| **SBOL Visual Version** | 1.1 |
| **Status** | Draft |
| **Created** | 01-Jul-2017 |
| **Last modified** | 03-Sep-2017 |
## Abstract

Glyphs need some additional information about how they are to be used, as failing to specify this has caused confusion. In particular:

* What their recommended relative scale is.
* Whether they "tightly" fill their bounding box or whether there are expected to be gaps at the edges
* Which, if any portions, are the "interior" of the glyph, to be affected by fill choices
* How the glyph is recommended to be aligned with the nucleic acid backbone.

## Table of Contents  <remove TOC if SEP is rather short>
- [1. Rationale](#rationale) 
- [2. Specification](#specification)
- [3. Example or Use Case](#example)
- [4. Backwards Compatibility](#compatibility)
- [5. Discussion](#discussion)
- [References](#references)
- [Copyright](#copyright)

## 1. Rationale <a name="rationale"></a>

We've run into problems with ambiguity in some glyphs, in which people are confused about how to use a glyph in several areas. This aims to add explicit guidance on how to resolve these issues to the specification of each glyph.

### 2.1 Relative scale

Glyphs are RECOMMENDED to use the same relative scale to one another as found in the specification.

This just makes formal something that has been informally interpreted in this way already. All of the original SBOL Visual 1.0 glyphs were specified on a 0.5 x 0.5 inch template, so this should probably be the base for future glyph design as well.

### 2.2 Bounding Box

Every glyph specification MUST include a grey rectangular bounding box. Glyph interactions with one another and with the nucleic acid backbone are defined in terms of the bounding box, not the lines of the glyph.

This allows "gaps" at the edge of a glyph to be part of its expected specification.
Most significantly, a glyph can thus "hover" over the nucleic acid backbone, like primer binding sites generally do.

### 2.3 Interior

When a glyph has an intended interior (i.e., spaces within the boundary that may be filled with color or pattern), the interior MUST be specified as a grey filled area.

This avoids ambiguity in which spaces are intended to be "inside" versus which may simply be closed lines.

### 2.4 Recommended Backbone alignment

Every glyph for representing a Component MUST have exactly one grey horizontal line indicating the RECOMMENDED vertical positioning of the glyph on a nucleic acid backbone. 

Note that it is only recommended, and thus people can continue using alternate placements if they have good reason for doing so. Additional recommendations for best practices in alignment beyond this may be added to glyphs if desired as well.

## 3. Examples <a name='example'></a>

CDS glyph, with interior marked and a possible recommended vertical alignment of the backbone to the bottom of the glyph:
![image](https://user-images.githubusercontent.com/10675899/27767070-cccbd9ee-5e9d-11e7-9d87-9b4f050a5dbe.png)

Insulator with one possible interpretation of the interior marked:
![image](https://user-images.githubusercontent.com/10675899/27766997-689f0a98-5e9a-11e7-977a-d3aba2359f56.png)

Primer binding site, "hovering" over the nucleic acid backbone:
![image](https://user-images.githubusercontent.com/10675899/27767075-1c929aa8-5e9e-11e7-9213-45f70eb2da20.png)

## 4. Backwards Compatibility <a name='compatibility'></a>

For most glyphs, the bounding box, interior and alignment are obvious. 
For some, however, this is not the case, and these will need to be voted on to ensure consensus.

## Copyright <a name='copyright'></a>

<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="sbolstandard.org">
    <span property="dct:title">SBOL developers</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">SEP V001</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="US" about="sbolstandard.org">
  United States</span>.
</p>

**Comment by bbartley** [comment]
If all of the SBOL Visual glyphs are specified on a 0.5 x 0.5 inch template, what specifies the boundary box's position within this template?

Thanks!
Bryan

**Comment by jakebeal** [comment]
I have clarified my wording.  The idea is that the bounding box is another box drawn on the glyph specifications --- see my examples here.

**Comment by jakebeal** [comment]
Changes implied by this SEP are drafted in https://github.com/SynBioDex/SBOLv-realizations/tree/feature/glyph-specs

**Comment by swapnilb** [comment]
I have a questions regarding the **_Bounding Box_**. Are constraints specified relating to the Bounding Box of a glyph, suggestions or mandatory? For example would it rule something like 
![image](https://user-images.githubusercontent.com/1002777/27925221-f9cff49a-6251-11e7-8a2f-d399c70576bf.png)
as noncompliant because bounding boxes of p2 and r2 intersect?
If so, what is the benefit? If a future glyph is "bushy," might all the canopy waste valuable space? And how do bounding boxes work with visualizing current and future interactions among glyphs -- I suppose there some overlap is inevitable?

**Comment by jakebeal** [comment]
One of the purposes of bounding boxes is to let us meaningfully talk about the p1/r1 vs. p2/r2 in your example.  No specific proposal for what, exactly, to do with bounding boxes is attached to this proposal: that will come up in a later proposal.

In that proposal we will suggest that overlapping glyphs should generally be interpreted to mean overlapping positions on the backbone (as is often the convention already), and thus RECOMMEND that bounding boxes overlap if and only if positions overlap.

**Comment by swapnilb** [comment]
The "if and only if" is not something I would support recommending, because there is very little benefit. I would, in the later proposal, suggest changing it to "if."

**Comment by jakebeal** [comment]
That's fine; we can deal with that discussion in the later proposal.  Right now, the plan is to make sure that bounding boxes are a thing, which is definitely necessary for supporting near-but-not-touching glyphs like primer binding site.

**Comment by rsc3** [comment]
i dont like the definition of interior given with quotes, we should expand on what interior means for clarity

**Comment by jakebeal** [comment]
@rsc3 I have attempted clarification.

**Comment by chofski** [comment]
I'd also suggest editing abstract as follows: "How the glyph is recommended to be aligned with the nucleic acid backbone (and other glyphs if appropriate)." @swapnilb raises an important point, that is probably more relevant for some glyphs that almost always overlap with others (primer binding sites are a good example). Would be good to recommend that alignment to both backbone and other parts is provided in the definition.

**Comment by jakebeal** [comment]
@chofski Can you please give an example of a additional alignment information that would be useful to include, besides the vertical alignment of the backbone and the bounding box?  I am reluctant to add this in without an example, because it changes the specification away from the simplicity of "one RECOMMENDED vertical alignment rule"

**Comment by chofski** [comment]
If the part is commonly overlapping, then the additional alignment information would be in respect to existing part bounding boxes at its position. So for a forward facing primer binding site, vertical alignment would be for the bottom edge of the bounding box to touch the backbone when no other parts present, or for the bottom edge of the bounding box to touch the upper most top edge of any overlapping parts. This sort of statement should be optional as most parts won't need to worry about it, but it should be suggested I believe for those that are commonly annotated within others (e.g. recognition sites, operator sites, etc).

**Comment by swapnilb** [comment]
Agree with @chofski suggestion above.
Should add something along the lines of: "Glyph definitions may include a list of rules for x-y aligning and positioning the glyph relative to other glyphs, and must include rules for x-aligning the glyph to the DNA backbone." Follow with some examples.

And in addition, would like to repeat/remind that "non overlapping bounding boxes" should not be a mandatory constraint, 

but, only that colocated parts must have x-aligned bounding boxes or something along those lines.

**Comment by jakebeal** [comment]
@chofski I have added a statement that glyphs may include additional recommended best practices for alignment, which I believe covers this.

@swapnilb Please recall that this proposal does not say anything about non-overlapping bounding boxes one way or another.

**Comment by jakebeal** [comment]
Accepted, and thus closed per SBOL procedure in updated SEP 001.
