### ISSUE TITLE
Add SEP V011, SEPV012 glyphs to font

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#46]
The new font was added just shortly before we adopted SEP V011 and SEP V012: we need to add the new symbols that have just been added to the spec to the font.

@BenjaminAleritsch would you be willing to do this update, or do you want somebody else to do it?

**Comment by cjmyers** [comment]
Has this been done?

**Comment by jakebeal** [comment]
Yes, these were resolved in #65
