### ISSUE TITLE
SEP V003: Distinguished Unknowns

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#6]
# SEP V003: Distinguished Unknowns

| SEP | <leave empty> |
| --- | --- |
| **Authors** | Jacob Beal (jakebeal@ieee.org) |
| **Editor** | <leave empty> |
| **Type** | Specification |
| **SBOL Visual Version** | 1.1 |
| **Status** | Draft |
| **Created** | 21-Jul-2017 |
| **Last modified** | 17-Aug-2017 |
## Abstract

We need a way of distinguishing between three distinct use cases that are currently all covered by the "User Defined" symbol.  These are:

* Unspecified: SO:0000110 Sequence Feature
* No glyph assigned: Any SO term that is not covered by any glyph besides the root Sequence Feature
* Composite: SO:0000804 Engineered Region

Accompanying with the Composite proposal is also a proposal for an Omitted Detail glyph explicitly showing where information is not being represented.

## Table of Contents  <remove TOC if SEP is rather short>
- [1. Rationale](#rationale) 
- [2. Specification](#specification)
- [3. Example or Use Case](#example)
- [4. Backwards Compatibility](#compatibility)
- [5. Discussion](#discussion)
- [References](#references)
- [Copyright](#copyright)

## 1. Rationale <a name="rationale"></a>

Importing large numbers of constructs has found three distinct cases that need to be visually distinguished but currently are all lumped under 'User Defined":

* "Unspecified": Constructs whose type information is missing --- here called "Unspecified," and typically defaulting to the root term SO:0000110.  Here, we want people to recognize the problem and fill in the missing information.
* "No Glyph Assigned": Constructs with a well-defined and interesting type that happens to not be covered by any of the current glyphs. Here, we want people to recognize that the part is well understood, just outside the current vocabulary. We also want them to make new glyph proposals.
* "Composite": Potentially complex designs composing multiple parts. Here we want to have people recognize that there is more detail available.

The Unspecified glyph is intended for showing where a sequence's role is missing (or, equivalently, given only the uninformative "Sequence Feature" root role). It should never appear with well-curated designs or diagrams.

No Glyph Assigned is intended for constructs with a defined specific role that happens to not yet be covered by available approved glyphs (other than the root "Sequence Feature"). It is more likely to appear in machine-generated diagrams than in human-generated diagrams, since humans are likely to invent and use their own glyph for the purpose.

Some of the proposed glyphs for Composite are linked to the proposal for an Omitted Detail glyph.

## 2. Specification <a name="specification"></a>

The "User Defined" glyph will be split into three new glyphs: "Unspecified", "No Glyph Assigned", and "Composite".

A number of proposals have been made for these glyphs, from which we need to pick one to be RECOMMENDED for each and may choose to pick others as alternatives.

Currently, all three of these meanings are covered by the "User Defined" glyph, a plain rectangle suggesting a blank slate to be written upon:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/user-defined-specification.png)

### Unspecified and No Glyph Assigned 

A number of potential replacement glyphs and variants have been proposed for covering Unspecified and/or No Glyph Assigned.  The current supported candidates are:

#### Unspecified

* The unicode "replacement character" glyph, indicating a missing or invalid symbol, will be RECOMMENDED:

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/replacement-glyph-specification.png)

* A half-rounded rectangle, the SBGN glyph for a nucleic acid, will be an alternative:

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/halfround-rectangle-specification.png)

#### No Glyph Assigned

_Per discussion, No Glyph Assigned has been deferred to SEP V006._

* Keep the current "User Defined" rectangle as RECOMMENDED.

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/user-defined-specification.png)

Alternate stylings of this rectangle might be preferred by users and tools:

* A tall thin rectangle, which some fonts use as an alternative "replacement character":

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/tall-rectangle-specification.png)

* A dashed line rectangle, implying something is missing:

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/dashed-rectangle-specification.png)

### Composite 

For Composite the following glyph has been proposed to become RECOMMENDED:

* Dashed "expanding lines" connecting any "base" glyph representing the more abstract composite (e.g., Omitted Detail, or Terminator, or Promoter) to a backbone diagramming the contents of the composite. Note the bounding box is indicating the location of the base glyph, and would scale with that glyph.

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/6913ca8/Glyphs/user-defined/composite-base-symbol-specification.png)

### Omitted Detail

No SO term will be associated with this, as it is indicating that something is *not* being representing.

The proposed RECOMMENDED omitted detail glyph is break in the backbone with something to indicate that material would normally be in that location. In particular, from reasonable several alternatives, an ellipsis is proposed:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/omitted-detail/omitted-detail-ellipsis-specification.png)

Note that this glyph actually places a "break" in the nucleic acid backbone.

## 3. Examples <a name='example'></a>

Unspecified: an anonymous sequence that is missing any information about its nature or intended purpose.

No Glyph Assigned is intended to be used for any Component that is not covered by other SBOL Visual glyphs.

Composite: an "expression cassette" containing a ribosome entry site, coding sequence, and terminator.

Omitted Detail: A diagram in which a sequence features is not drawn.

## 4. Backwards Compatibility <a name='compatibility'></a>

The "User Defined" rectangle will remain as a RECOMMENDED or alternative glyph for all three of Unspecified, No Glyph Assigned, and Composite.

## 5. Discussion <a name='discussion'></a>

The following proposed options have been considered, but do not have strong support and are thus being removed from consideration unless they pick up significant advocacy. They may be revisited in the future.

### Unspecified or No Glyph Assigned 

* A horizontal line with a question mark over it:

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/blank-line-question-specification.png)

* A piece of DNA: 

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/dna-specification.png)
* A horizontal line:

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/blank-line-specification.png)

* A rectangle with an X through it:

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/X-rectangle-specification.png)

### Composite 

* Dashed "expanding lines" connecting an Omitted glyph (one candidate shown here for an example) to a backbone diagramming the contents of the composite. Note this glyph's bounding box is only the Omitted glyph.

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/composite-omitted-detail-specification.png)

* Dashed "expanding lines" connecting a point of the backbone to a backbone diagramming the contents of the composite.  Note that this glyph has no bounding box.

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/composite-point-specification.png)
* Dashed "expanding lines" connecting two bars to a backbone diagramming the contents of the composite. Note that this glyph has no bounding box.

  ![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/composite-bars-specification.png)
* A double rectangle:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/double-box-specification.png)

* A "black box":

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/black-box-specification.png)

### Omitted Detail

Brackets:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/omitted-detail/omitted-detail-brackets-specification.png)

Slanted "graph axis break":

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/omitted-detail/omitted-detail-slanted-specification.png)

Straight "graph axis break":

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/omitted-detail/omitted-detail-straight-specification.png)

## Copyright <a name='copyright'></a>

<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="sbolstandard.org">
    <span property="dct:title">SBOL developers</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">SEP V003</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="US" about="sbolstandard.org">
  United States</span>.
</p>

**Comment by jakebeal** [comment]
My personal preferences are as follows:

* Unspecified: RECOMMEND the "Replacement Character"; allow SBGN half-round rectangle and old rectangle glyph as alternatives; discard the rest.
* No glyph assigned: RECOMMEND the tall-thin rectangle; allow old rectangle as alternative; discard the rest.
* Omitted Detail: RECOMMEND the brackets, discard the rest (I'd be OK with the slanted break too).
* Composite: RECOMMEND the "expand from omitted", discard the rest.

**Comment by 3ach** [comment]
I agree with @jakebeal with regards to Composite and Omitted Detail. For Unspecified, I agree that 'replacement character' is a good RECOMMEND candidate, but think the SBGN half-round rectangle should be discarded and the horizontal line with a question mark kept in its place. For no glyph assigned, I think we should RECOMMEND the dashed-line rectangle, allow the old rectangle, and discard the rest.

**Comment by jakebeal** [comment]
Thanks @zachzundel: would you be willing to expand on what you like about "horizontal line with a question mark"?

**Comment by jamesscottbrown** [comment]
Jake, I think you might have composite and omitted reversed in your list of preferences. Do you mean:

**Omitted detail**: RECOMMEND the brackets, discard the rest (I'd be OK with the slanted break too).

**Composite**: RECOMMEND the "expand from omitted", discard the rest

?

**Comment by 3ach** [comment]
@jakebeal the reason for discarding the SBGN glyph and using the 'horizontal line with question mark' glyph is that I think the horizontal line glyph represents more intuitively an unspecified character. I think the SBGN glyph is unclear and would like a user to be able to roughly infer the meaning from glyphs without holding a reference card.

**Comment by cjmyers** [comment]
Discarding completely though then would not yield one of our goals which is an SBGN diagram is a legal SBOLv 2 diagram.  I agree it is not ideal, but when it is unknown what glyph to use, there is no ideal solution I think.

**Comment by jakebeal** [comment]
Thank you, @jamesscottbrown, you are correct --- I have switched them back to the right order.

**Comment by jakebeal** [comment]
@cjmyers @zachzundel Remember, it is not a question of "SBGN NA" vs. "line with question mark." We do not have to have any alternatives, and we can have multiple alternatives. Thus, each should be considered independently.

The test that I propose for considering a proposed alternative is as follows: **is there are strong reason, other than personal aesthetics, that this alternative could be preferred in a diagram over the RECOMMENDED symbol?**

* With regards to "line with question mark," I think it's a fine symbol, but am unclear whether there is any reason to prefer it over "Replacement Character." I am open to hearing such.

* With regards to "SBGN NA," I find the symbol problematic with respect to our glyph criteria, but understand the case for using it if one wants to use SBGN symbols wherever possible.

**Comment by bbartley** [comment]
With regards to "COMPOSITE: expand from omitted", I see there is a kind of logical consistency to it.  However, in most cases, I don't think  we want to "expand from omitted".  Consider what would happen if we collapsed the expansion.  All we are left with is an omitted symbol.  What if I don't want to omit the root level symbol?  For example, how do I expand a promoter or terminator to show its substructure?

**Comment by jakebeal** [comment]
@bbartley It sounds like what you are suggesting is that the symbol be generalized to "expand from root symbol", and then in many cases the root symbol would be "omitted"?

**Comment by bbartley** [comment]
@jakebeal yes, I like that generalization!

**Comment by jakebeal** [comment]
@bbartley I have updated the SEP and branch accordingly, and am switching my preference to "expand from base symbol"

**Comment by JS3xton** [comment]
Alrighty, let's see if I can keep this all straight...

## Unspecified
I like the use of a "?" in the glyph somehow. I'm lukewarm on the unicode "replacement character" glyph, though:

<img src="https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/user-defined/replacement-glyph-specification.png" width="75">

Although I think it's the best of the proposed options.

I will also propose the old "user defined" glyph with a "?" imposed on it:

<img src="https://user-images.githubusercontent.com/2179825/28655501-fcde9b9e-7261-11e7-83b7-27038684bdd1.png" width="100">

or perhaps with a dashed rectangle:

<img src="https://user-images.githubusercontent.com/2179825/28656140-cebdb764-7265-11e7-98b7-168d8d1d0384.png" width="100">

This makes the glyph somewhat backwards compatible, which could be helpful  ¯\\\_(ツ)\_/¯ . The jury is still out for me on if I like either one of those better, though.

I could maybe see the unicode "replacement character" glyph and the "horizontal line with a question mark over it" glpyh as alternatives, but, per the metric @jakebeal proposed, I don't see a strong reason why those glyphs would be preferred over either the unicode "replacement character" glyph or the glyphs that I proposed, so I'd vote to discard all but the RECOMMENDED glyph. (I admit, though, that I'm not familiar enough with this group to comment on the appropriateness of facilitating compatibility with SBGN symbols)

## No Glyph Assigned
I'm admittedly not a huge fan of the dashed rectangle proposed by @zachzundel because it makes the design feel incomplete. To the contrary, a "no glyph assigned" glyph is meant to represent a well-formed design; I think, if anything, the "unspecified" glyph could be a dashed rectangle because that glyph is meant to be replaced in a well-formed specification.

I'm also not a fan of the tall-thin rectangle proposed by @jakebeal, but I don't really have any good reason why.

As such, I would vote for the original "user defined" rectangle. Discard everything else.

## Omitted Detail
I don't like

<img src="https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/omitted-detail/omitted-detail-slanted-specification.png" width="75"> or  <img src="https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/omitted-detail/omitted-detail-straight-specification.png" width="75">

because they look like the "blunt restriction site" glyph:

<img src="https://user-images.githubusercontent.com/2179825/28654960-f04d4ba4-725d-11e7-8714-ffb985f067dc.png" width="40">

The brackets

<img src="https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/8423527/Glyphs/omitted-detail/omitted-detail-brackets-specification.png" width="75">

also look pretty similar to the "blunt restriction site" glyph, although for some reason I'm more willing to tolerate them. I think the ellipsis gets my vote, though. Or perhaps the brackets with an ellipsis inside? (again, to help differentiate the "omitted detail" glyph from the "blunt restriction site" glyph):

<img src="https://user-images.githubusercontent.com/2179825/28655207-ba83c51e-725f-11e7-8ea0-f572b6c4bbee.png" width="75">

Discard the rest.

## Composite
I agree with @jakebeal and @bbartley on the "expand from root" generalization. Discard the rest.

**Comment by jakebeal** [comment]
Thank you, everyone: it seems to me that we are actually rather close to consensus, and I have updated the SEP accordingly.  Here is what I see:

* **Unspecified:** "Replacement Character" has general support.  Furthermore, John's "?" rectangle proposals are covered as stylings of the backward-compatible rectangle from "User Defined."
* **No Glyph Assigned:** The candidates that people like are either the "User Defined" rectangle or scaled/style variants.  We can cover all of them just by keeping "User Defined"
* **Composite:** "Expanding lines from root" has general support.

That leaves the following open questions, which seem to be in good state for resolution by a vote:

* Should "Unspecified" also allow the SBGN half-round rectangle?
* Should "Omitted" be brackets, ellipsis, or both?

I am going to encourage more discussion, then move for a vote.

**Comment by 3ach** [comment]
@JS3xton the reason that I proposed the dashed-rectangle for 'no glyph assigned' is actually the incomplete feeling it gives to the design. Ideally, this would indicate a place where a new glyph could be proposed, and (hopefully) a user who was trying to represent something without a glyph would be the kind of person familiar with existing solutions that they could propose a good new glyph.

**Comment by chofski** [comment]
Most of the worked out suggestions look good in my opinion. My only disagreement is on the omitted detail. I agree that the ellipse is a good option. I also *strongly* support the use of the slanted axis break notation. This type of break is well understood both from their use in graphs, but also in general engineering drawings. In addition, there should be the option to have a single slanted line if nothing further will be detailed in the design. I also dislike the square bracket notation as that has other meanings in other related fields. I worry it might add confusion, for example, bioinformaticians may think there is something *optional* missing? Happy to tolerate if the ellipse are present, but then, why not only use them to keep the symbol simple?

**Comment by jakebeal** [comment]
Thanks, @chofski: I have added slanted graph break back to the backed candidates.

**Comment by jakebeal** [comment]
I would like to move forward with this proposal. I think that it would be good if we were able to prune the number of variants, however.  Here are my questions to all of you:

- On "unspecified", "replacement character" has strong support.  Would anybody object to dropping the highly similar "horizontal line with a question mark" as a variant?
- On "omitted detail", there are three significantly different glyphs being backed. Despite my expressed preference, I could potentially be happy with any of the three. I strongly believe, however, that it would be a good idea to not adopt all three, since they don't really serve different purposes. How do other people feel about dropping some of the alternatives?

**Comment by cjmyers** [comment]
Fine with dropping horizontal line/question mark.

Fine with a vote that picks just one omitted detail variant.  Don't care which one either wins this vote, but happy to have a vote to pick exactly one.

**Comment by jakebeal** [comment]
Anyone else? I plan to move on this shortly if there is no objection.

**Comment by chofski** [comment]
I'm happy with this.

**Comment by bbartley** [comment]
I have a couple minor concerns, which may or may not affect this proposal moving forward:
* On omitted, the slash lines indicating the break are easier to draw by hand, in my experience, which would be one argument for keeping this variant 
* On No Glyph Assigned, can the "tall thin rectangle" be interpreted as a simple tick mark?
* One category of symbol we have not discussed in this proposal is "Ignored", which should minimize a symbol to something which does not clutter the GUI or distract the eye.  Does anyone else have concerns about this?  For example, in my visualization tool, I may want to customize my view by ignoring certain types.  For example, maybe I want to hide `assembly_component (SO:0000143)` or view only `oligos (SO:0000696)`

Best
Bryan

**Comment by jakebeal** [comment]
With regards to the points you raise:

- On omitted: this is another argument pro/con the various options.  My key question from above though: are you in favor of having the vote pick precisely one variant?
- On No Glyph Assigned: no, it cannot be a tick mark, since it has an interior (and the tick would conflict with Restriction Site).
- I would like to defer possible separation of "ignored" from "omitted" for separate proposal.

**Comment by bbartley** [comment]
> are you in favor of having the vote pick precisely one variant?

I'm a little uneasy with choosing precisely one variant for omitted detail. They each have their strengths in a particular context:

1. Brackets are great for visualization tools
2. Ellipses are established convention for "omitted" in nucleotide alignments in sequence editor tools.  Consequently I have adopted this convention for glyph alignments using SBOL tools, using it in my presentations.  I have found that it is easy for biologists to comprehend because it is consistent with what they have are already experienced.
3. Slashes are easy for hand-drawn communication 
(admittedly, I don't know how important is 3, but 2 is highly important to me)

**Comment by bbartley** [comment]
An entirely separate issue, but one which I would like to see addressed before proceeding is:
*  Does Composite have a "collapsed", in addition to "expanded" representation?

**Comment by jakebeal** [comment]
> Does Composite have a "collapsed", in addition to "expanded" representation?

In this proposal, the "collapsed" representation is the base glyph.  You are, of course, free to choose additional styling conventions such as fill to indicate that there is additional complexity hidden in this composite.

**Comment by jakebeal** [comment]
Re-reading through the total discussion of Omitted Detail, I find that while nobody really loves ellipsis, it's the only one that nobody raises any specific objection to either.  Combining that with Brian's observation that it's an emerging or established convention in sequence editing tools, and I think it makes sense to propose the ellipsis as the recommended symbol for Omitted Detail.  It's also pretty easy to draw by hand, so it meets Brian's point 3 as well.

I would then propose that we adopt in this state, and then after working with ellipsis for Omitted Detail a while, if we find that we are really missing out from not having one of the other options, we can revisit and add it as an alternative.

**Comment by bbartley** [comment]
Just to put a concrete example behind my claims, here is a figure indicating the convention I'm talking about:
http://www.nature.com/nrg/journal/v3/n5/fig_tab/nrg798_F1.html?foxtrotcallback=true

**Comment by jakebeal** [comment]
Based on our discussion, I have updated the proposal and will move it for a vote.

**Comment by jakebeal** [comment]
Accepted and integrated, and thus closed per SBOL procedure in updated SEP 001.
