### ISSUE TITLE
SEP V015: Change BioPAX to SBO

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#62]
Molecular Species glyphs are currently defined in terms of BioPAX terms, which is limiting and does not match with SBO used for Interactions and Interaction Nodes. This SEP proposes changing to SBO, keeping BioPAX as an alternative for backward compatibility until SBOL 3.0.

Read the full SEP at: https://github.com/SynBioDex/SBOL-visual/blob/master/SEPs/SEP_V015.md
Complete draft spec change at: https://github.com/SynBioDex/SBOL-visual/tree/SEP-V015

**Comment by palchicz** [comment]
Discussed offline, but I'd like to document it here. @cjmyers @jakebeal is this SEP ready for a vote?

**Comment by cjmyers** [comment]
I’m okay with it moving forward now.

**Comment by jakebeal** [comment]
Concur!

**Comment by palchicz** [comment]
linking to more discussion in this thread: https://groups.google.com/d/topic/sbol-visual/oJL_Xg04pjg/discussion

**Comment by jakebeal** [comment]
Closed by #66

**Comment by palchicz** [comment]
As per procedure, these issues don't get closed until incorporated into the SPEC

**Comment by palchicz** [comment]
nm, I see now that it was incorporated. My mistake

**Comment by jakebeal** [comment]
It goes like lightning since I like to set up the spec change as part of drafting the SEP. :-)
