### ISSUE TITLE
SBOL for 2A sequences 

### ISSUE THREAD

**Issue by Jihwan-Lee1** [SynBioDex/SBOL-visual#70]
Hi, 

I am trying to use a SBOL glyph to show 2A sequences. Unfortunately, there isn't a glyph for it. The best alternative I can find at the moment is the protein cleavage site. 2A sequences, however, are not protease cleavage sites. Instead, they work by 'skipping' a peptide bond formation step during translation. Would there be a good glyph to represent this?

**Comment by jakebeal** [comment]
I thought that 2A sequence were self-cleaving peptide sequences rather than "skips"? If this is the case, would this term, http://www.sequenceontology.org/browser/current_release/term/SO:0001061 be an appropriate descriptor?

The SBOL Visual glyph is supposed to be a general protein cleavage site and not just for protease, so we might add this sense to the glyph as well.

**Comment by shyambhakta** [comment]
It's only colloquially "self-cleaving." Now it's known that such peptide sequences alter the ribosome upon translation, causing release of the nascent peptide while allowing translation to continue on the remainder of the CDS.
Sure, it skips a peptide bond formation, but there must also be some mechanism for hydrolysis of the nascent chain and the A-site tRNA it's attached to. Whether the release factor does it as it normally does, or whether it happens some other way, there is hydrolysis, but it's not hydrolysis of a peptide bond, but an an amino acid - nucleic acid bond.

In any case, given that the result is indistinguishable from proteolytic cleavage (if a protease targeting that sequence were to exist), it may be fine to use the protein cleavage site glyph.

**Comment by jakebeal** [comment]
So, for @Jihwan-Lee1 , I think that the recommendation is to the Protein Cleavage Site (https://github.com/SynBioDex/SBOL-visual/tree/master/Glyphs/cleavage-site), even though it's not a protease, and we will update the glyph to include the more general notion.

@shyambhakta : I'm thinking that cleaved_peptide_region would then be the best term to add to the glyph? Would you agree? http://www.sequenceontology.org/browser/current_release/term/SO:0100011

**Comment by Jihwan-Lee1** [comment]
Hi guys, thank you for the replies! 
If the glyph is not just for protease cleavage site, then I think it can be used for now. It will be good if the glyph gets updated as 2A sequences are commonly used in eukaryotes for multi-cistronic gene expression! Hmm. For the 'cleaved_peptide_region' discussion, I don't think it is a 100% suitable descriptor. The description says: _The cleaved_peptide_region is the region of a peptide sequence that is cleaved during maturation_. People usually link maturation as post-translational process, but for 2A "cleavage" it occurs **during** translation. But then, I don't see a good alternative.

**Comment by shyambhakta** [comment]
The parent and children terms for cleaved_peptide_region imply that such a region is "trash", absent in the mature form. Inteins remove themselves from proteins. N-/C-terminal peptides and often the initiator methionine are cleaved off, absent in the final, mature form.
The 2A peptide isn't removed from the protein, so cleaved_peptide_region isn't applicable.

**Comment by jakebeal** [comment]
I've opened an issue on Sequence Ontology to either adjust the term or make a new term, as the maintainers think best.  Once that's resolved, we can adjust the glyph to match.

**Comment by Jihwan-Lee1** [comment]
Thanks! Greatly appreciated it!

**Comment by jakebeal** [comment]
Thank you to you as well, @Jihwan-Lee1 , for bringing this issue to our attention.

**Comment by jakebeal** [comment]
Looks like we are likely to get a new term, which we can add to the glyph.
My [current suggestion to the SO maintainers](https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/475#issuecomment-542337123) is:

> A 2A_self_cleaving_peptide is a polypeptide region that can result in a break in the peptide sequence at its terminal G-P junction.

I have specifically tried to be vague about the mechanism for the break, since that's not clear.
@shyambhakta @Jihwan-Lee1 : does this sound like a good definition to you, or do you see changes that should be made?

**Comment by Jihwan-Lee1** [comment]
@jakebeal  Thanks for all the help! I think the current definition is too general and might encompass other non-2A peptides. I think we should mention that the break/cleavage occurs during translation. I think this makes the definition more specific for the 2A sequences.

**Comment by jakebeal** [comment]
@Jihwan-Lee1 Can you suggest language?

**Comment by jakebeal** [comment]
The new term for 2A sequences is officially added to Sequence Ontology: http://www.sequenceontology.org/browser/current_release/term/SO:0002224

We can now proceed to add it to the Protein Cleavage Site glyph as well.

**Comment by jakebeal** [comment]
I've submitted an SEP for adding 2A sequences: https://github.com/SynBioDex/SBOL-visual/issues/78

**Comment by jakebeal** [comment]
@Jihwan-Lee1 We're about to release version 2.3 of the specification, and I'd like to add your name to the author list but cannot find information via your account.  Can you please send this information?

**Comment by Jihwan-Lee1** [comment]
Hi Jake, 

 

Thank you for the consideration! 

My name is “Jihwan Lee”. 

My affiliation is Systems, Synthetic, and Physical Biology Program, Rice University.  

 

Best,

 

James Lee (I go by James).

 

Ph.D. Student | Systems, Synthetic, and Physical Biology Program, Rice University
Graduate Research Assistant | St-Pierre Lab, Neuroscience Department, Baylor College of Medicine stpierrelab.com <https://www.stpierrelab.com/> 
(832) 245-1790 | jl162@rice.edu <mailto:jl162@rice.edu> 



PS I think I saw you in one of the virtual iGEM judge meeting 😊 I was one of the judges too.
