### ISSUE TITLE
SEP V019: Allow Complex to Include DNA Backbone

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#74]
A molecular species in contact with a DNA backbone is often used to show binding into a complex in a diagram.  This SEP proposes a modification to support such diagrams.

Read the full SEP at: https://github.com/SynBioDex/SBOL-visual/blob/master/SEPs/SEP_V019.md

**Comment by shyambhakta** [comment]
So if I am to understand, a protein glyph representing a transcription factor to be shown binding a promoter's operator can either be shown superimposed with a promoter glyph OR shown superimposed/placed close above a binding site glyph next to the promoter that represents an operator.

**Comment by jakebeal** [comment]
That's right.  Or it can be shown in the old way, not touching at all, but with an interaction edge linking it to stimulate / inhibit / control the promoter.

**Comment by JS3xton** [comment]
Thanks @jakebeal for drawing up an SEP for this.

I don't see the need to discourage superimposing glyphs on a nucleic acid backbone:
>If binding is being shown, the molecular species glyph SHOULD contact an appropriate sequence feature glyph (e.g., for a binding site or restriction site) **and not the backbone itself** (see example in Appendix A.2 for glyph Complex).

but this is a minor issue.

I also think the example of a protein binding the upper left corner of the promoter glyph looks funny. With less detail, I prefer the protein superimposed on the DNA backbone within the promoter glyph:
![bound_promoter](https://user-images.githubusercontent.com/2179825/66728586-6ea70000-ee0b-11e9-8730-7c326e017f21.png)

And if you want to show more detail, perhaps with binding site glyphs, I might use the composite glyph:
![bound_promoter2](https://user-images.githubusercontent.com/2179825/66728591-75357780-ee0b-11e9-9bcd-b8d7b30cf0cb.png)

**Comment by jakebeal** [comment]
@JS3xton Can you elaborate on why you think one shouldn't avoid the backbone?  I was thinking that it would add potential ambiguity.

**Comment by JS3xton** [comment]
Superimposing the protein glyph and the nucleic acid backbone seems most literally correct to me. The transcription factors in question often bind directly to DNA to form a complex, and we show complexes by superimposing the glyphs of the constituent species. Here, that means superimposing a nucleic acid glyph (whether that's a backbone line or a single- or double-stranded nucleic acid glyph) and the protein glyph.

**Comment by jakebeal** [comment]
Why not show it binding to a binding site glyph, then, rather than a feature-free section of backbone?

**Comment by JS3xton** [comment]
That's certainly fine by me, and perhaps even superior in many cases. I don't think we should mandate it, though, when a protein glyph contacting a feature-free backbone is still perfectly interpretable (and, for particularly complex diagrams, necessarily simpler). I think it should be up to the illustrator to decide how best to convey their point.

So perhaps using a binding site glyph should be a SHOULD requirement and omitting the binding site glyph and superimposing a protein glyph on a feature-free section of backbone could be a MAY requirement. That way both are permitted, but a preference is still codified. The current language doesn't convey that clearly as I read it.

**Comment by jakebeal** [comment]
I've updated SEP V019 per this discussion: https://github.com/SynBioDex/SBOL-visual/blob/master/SEPs/SEP_V019.md

Please take a look and let me know what you think.

**Comment by JS3xton** [comment]
> This may also be applied to show complex formation (binding) of a molecule to a nucleic acid backbone by compositing the glyph for the molecule with appropriate portion of the diagram the nucleic acid backbone. For example, a protein binding to the promoter of a functional unit:

In this addition, the end of the first sentence is a little choppy, and I might say "transcription unit" instead of "functional unit", but otherwise looks good to me! Thanks @jakebeal.

**Comment by jakebeal** [comment]
"transcriptional unit" to "functional unit" change made; if you have a suggested rephrasing of the first sentence, I'll be happy to add it.

**Comment by JS3xton** [comment]
Perhaps:

> This may also be applied to show complex formation (binding) of a molecule to a nucleic acid backbone by compositing the molecule glyph with the appropriate portion of the nucleic acid backbone.

**Comment by jakebeal** [comment]
Good idea; I made that change, and also changed "nucleic acid backbone" to "nucleic acid construct", since it's both glyphs and backbones.

**Comment by jakebeal** [comment]
Closing as accepted and incorporated.
