### ISSUE TITLE
SEP V004: New Glyph Proposal Collection

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#8]
# SEP V004: New Glyph Collection

| SEP | <leave empty> |
| --- | --- |
| **Authors** | Jacob Beal (jakebeal@ieee.org) |
| **Editor** | <leave empty> |
| **Type** | Specification |
| **SBOL Visual Version** | 1.1 |
| **Status** | Draft |
| **Created** | 22-Aug-2017 |
| **Last modified** | 18-Sep-2017 |
## Abstract

A number of new glyphs have been proposed over the past few years, and we need to put them to an up-or-down vote. 

There are twelve proposals currently pending: Aptamer, Codon, Homology Region, Inverter, Non-Coding RNA, ORI-T, polyA Site, Protein Domain, Specific Recombination Site, Non Directional Sticky End, Tag, Transcript Region

## Table of Contents  <remove TOC if SEP is rather short>
- [1. Rationale](#rationale) 
- [2. Specification](#specification)
- [3. Example or Use Case](#example)
- [4. Backwards Compatibility](#compatibility)
- [5. Discussion](#discussion)
- [References](#references)
- [Copyright](#copyright)

## 1. Rationale <a name="rationale"></a>

Each glyph detailed below in its specification has been provided with an individual rationale for that glyph.  Examples are also embedded within each proposal.

#### Associated SO term(s)
SO:0000031: Aptamer

#### Recommended Glyph and Alternates
The proposed aptamer glyph is a cartoon diagram of nucleic acid secondary structure like that found in aptamers:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/aptamer/aptamer-A-specification.png)

#### Prototypical Example

theophylline aptamer

#### Associated SO term(s)
SO:0001263: Non-Coding RNA Gene
SO:0000834: Mature Transcript Region 

#### Recommended Glyph and Alternates
Two of the proposed non-coding RNA glyphs are both single-stranded RNA "wiggles," one on top of a box:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/0cac2206/Glyphs/non-coding-rna/ncrna-boxC-specification.png)

another hovering above the backbone:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/non-coding-rna/ncrna-hover-specification.png)

One or the other of these should be chosen, but not both.

#### Prototypical Example

gRNA

#### Associated SO term(s)
SO:0000724: Origin of Transfer

#### Recommended Glyph and Alternates
The origin of transfer glyph is circular like Origin of Replication, but also includes an outbound arrow:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/15b47bb/Glyphs/origin-of-transfer/origin-of-transfer-C-specification.png)

#### Prototypical Example

oriT

#### Notes
The recommended backbone location of Origin of Replication is not yet fixed; the backbone location of this glyph is intended to match Origin of Replication, so it that is recommended to become below the glyph, this backbone location will shift as well.

#### Associated SO term(s)
SO:0000553: polyA Site

#### Recommended Glyph and Alternates
The polyA site glyph is a sequence of As sitting atop the backbone:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/polyA/polyA-specification.png)

#### Prototypical Example

polyA tail on mammalian coding sequence

#### Associated SO term(s)
SO:0000299: Specific Recombination Site

#### Recommended Glyph and Alternates
The specific recombination site glyph is a triangle, centered on the backbone, as has appeared in a number of recombinase circuit papers:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/specific-recombination-site/specific-recombination-site-specification.png)

#### Prototypical Example

flippase recognition target (FRT) site

#### Notes
Potential conflict with proposed Inverter glyph.

## 3. Examples <a name='example'></a>

See examples in individual glyph proposals.

## 4. Backwards Compatibility <a name='compatibility'></a>

All proposals are for new glyphs that do not conflict with existing glyphs. Note that two proposals (Inverter and Recombinase Site) do conflict with one another.

## 5. Discussion <a name='discussion'></a>

The following proposed options have been considered, but do not have strong support and are thus being removed from consideration unless they pick up significant advocacy. They may be revisited in the future.

### Aptamer

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/aptamer/aptamer-B-specification.png)

#### Associated SO term(s)
SO:0000360: Codon

SO:0000318: Start Codon

SO:0000319: Stop Codon

#### Recommended Glyph and Alternates
The proposed aptamer glyphs are two versions of a cartoon diagram of nucleic acid secondary structure like that found in aptamers:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon-specification.png)

Nucleotides can be indicated with colors or letters in the boxes:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_nucleotides.png)![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_colored.png)

Proteins can be indicated by a letter above:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_labelled.png)

Stop and start codons might be indicated by special symbols:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_start.png)![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_start%20(1).png)![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_stop.png)

Edits can be indicated by changes:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_edited%20(1).png)![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_edited_some.png)![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_edited_all.png)![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_edited_colored.png)![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_edited_nucleotides.png)![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/codon/codon_nucleotides_edited.png)

#### Prototypical Example

UGA stop codon

#### Notes
If accepted, there will need to be additional work done to elaborate the full specification.

#### Associated SO term(s)
SO:0000853  

#### Recommended Glyph and Alternates
The homology region glyph is a stretched hexagon hovering above the backbone:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/homology-region/homology-region-specification.png)

#### Prototypical Example

*Needs a good example*

#### Associated SO term(s)
*No SO term currently exists*

#### Recommended Glyph and Alternates
The inverter glyph is a triangle, echoing the buffer glyph from electronics.  It might be either above or on the backbone.

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/inverter/inverter-specification.png)

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/inverter/inverter-specification-above.png)

#### Prototypical Example

*Needs a good example*

#### Notes
Potential conflict with proposed Specific Recombination Site glyph.

### Non-Coding RNA

Squiggle with teeth:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/e0712eb/Glyphs/non-coding-rna/ncrna-hover-teeth-specification.png)

Peeling comb suggesting an RNA sequence partially attached to the backbone:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/transcript-region/transcript-region-specification.png)

#### Associated SO term(s)
SO:0001692 (unspecified direction)

#### Recommended Glyph and Alternates
A sticky restriction site of unspecified direction is an angled set of cuts:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/sticky-restriction-site/sticky-restriction-site-specification.png)

#### Prototypical Example

EcoRI restriction site.

### ORI-T
Spirals outward toward a new destination rather than being a closed circle. Two slightly different variants of spiral are proposed for consideration:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/origin-of-transfer/origin-of-transfer-specification.png)

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/origin-of-transfer/origin-of-transfer-B-specification.png)

#### Associated SO term(s)
SO:0000417 Polypeptide Domain

#### Recommended Glyph and Alternates
A number of proposals have been made for Protein Domain glyphs. These are:

* A chevron, which composes nicely with the standard CDS pentagon

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/protein-domain/chevron-specification.png)

* A plain rectangle (the same as user defined):

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/protein-domain/user-defined-specification.png)

* A chevron with a vertical break:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/protein-domain/broken-chevron-specification.png)

* A broken CDS pentagon

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/protein-domain/broken-cds-specification.png)

* A broken arrow (i.e., broken alternate CDS)

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/protein-domain/broken-arrow-specification.png)

* A CDS pentagon with a chevron break:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/protein-domain/broken-cds-chevron-specification.png)

#### Prototypical Example

VP64 activation domain

#### Notes
Protein domain should have the same recommended vertical position as CDS, but CDS does not have a recommended vertical position yet, so these proposals do not either.

#### Associated SO term(s)
SO:0000324: Tag

#### Recommended Glyph and Alternates
The tag glyph is a diagonal rectangle with clipped corners, reminiscent of a stereotypical paper gift tag:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/30935c/Glyphs/tag/tag-specification.png)

#### Prototypical Example

PEST tag

## Copyright <a name='copyright'></a>

<p xmlns:dct="http://purl.org/dc/terms/" xmlns:vcard="http://www.w3.org/2001/vcard-rdf/3.0#">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="sbolstandard.org">
    <span property="dct:title">SBOL developers</span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">SEP V004</span>.
This work is published from:
<span property="vcard:Country" datatype="dct:ISO3166"
      content="US" about="sbolstandard.org">
  United States</span>.
</p>

**Comment by jakebeal** [comment]
My take:
I like:
- Aptamer: Clearly getting used in many designs. I like the first of the two versions better.
- Non-Coding RNA: we need to distinguish functional RNAs like gRNAs from protein coding sequences, which are how they're getting represented now.
- ORI-T: if people want it, I like how it intuitively relates to our existing origin of replication glyph
- Protein Domain: people are already doing this in various ways, and we need a clear recommendation. I like the chevron variant best.
- Specific Recombination Site: this glyph has already been using in a number of publications and it's clean, simple, and asymmetric. 
- Tag: nice simple, intuitive symbol for something that is used in many cases.

I dislike:
- Codon: I think it's a lot of complexity for unclear demand.
- Inverter: there's no clear consensus on whether this makes sense as a basic part, and the proposed symbol overlaps with recombination site.
- Transcript Region: it's a fiddly symbol and I think Non-Coding RNA covers it well enough.

I am neutral on:
- Homology Region
- polyA Site
- Non Directional Sticky End

**Comment by swapnilb** [comment]
Recombinase sites have been in wide use in literature, so I would object to changing that glyph. I don't know what is meant by an inverter -- is this a device-level glyph? My impression is that our first pass (should) cover(s) biological primitive parts.

**Comment by jakebeal** [comment]
I'm not going to defend inverter --- it was made as a proposal, and we need to give it an up or down vote at some point. I will be voting "no" on inverter.

**Comment by swapnilb** [comment]
OriT was informally proposed by Angel Goni / @jakebeal / others in an SBOL Visual Thread (9/2014) to be the following:

![image](https://user-images.githubusercontent.com/1002777/29583084-ecf7f82e-874c-11e7-90b9-745de3e522f8.png)

I propose we consider it as a candidate glyph.

**Comment by jakebeal** [comment]
Thank you, Swapnil. I've added it, and like it very much as an option.

**Comment by swapnilb** [comment]
The "Tag" is somewhat confounding. The example cited is of a PEST tag, which appears to be a functional component (acts as a signal peptide for degradation). Yet, the SO term is specific to *oligo* tags used in identifying DNA; indeed, it's parent is an oligo.

I suggest we separate out which meaning is intended, and I also suggest we address "functional" tags (degradation, routing, fluorescence, etc) as well, if not before, identification tags, because the former have been used frequently in synthetic biology literature (e.g. Friedland et al. 2009).

**Comment by swapnilb** [comment]
Separately, my other objection to the Tag glyph is that it is not naturally scalable as may be needed to depict a sequence of varying length (whether functional, or oligo tag). It is also a simply rotated variant of another glyph, which makes us introduce two unrelated glyphs that are unnecessarily close.

**Comment by jakebeal** [comment]
Here is the current source for the Tag glyph proposal:

1. The iGEM registry has many parts with "Tag" as their class, e.g. [BBa_K1616026](http://parts.igem.org/Part:BBa_K1616026).  You can see the little "gift tag" icon on the page.
2. If you [search in SynBioHub for parts with a Tag role](https://synbiohub.org/search/role%3D%3Chttp%3A%2F%2Fwiki.synbiohub.org%2Fwiki%2FTerms%2Figem%23partType%2FTag%3E%26), you can readily find all of these, and see the "cleaned up" version of the glyph that is here.
3. Tags like these are commonly used, and it would be useful to be able to have glyphs for them, but to the best of my knowledge no other graphical convention currently exists.

You're right about the SO term being a problem, though --- if we can figure out what the right term is, that can be updated or fixed.

**Comment by mgaldzic** [comment]
The SO branch that deals with a peptide sequence binding site:
protein_protein_contact
http://www.sequenceontology.org/browser/current_svn/term/SO:0001093
 Maybe, a new sibling to PIP box
http://www.sequenceontology.org/miso/current_svn/term/SO:0001810 - note it
is also a polypeptide_region

Other tags may belong in, Experimentally added features will be separate...
not obviously consistent with the first...
http://www.sequenceontology.org/miso/current_svn/term/SO:0001697
-mike

**Comment by swapnilb** [comment]
Is anyone more familiar with http://obofoundry.org/ontology/pr.html -- has terms closer in meaning to some of the "functional" tags. (Some of the links don't appear to work.)

**Comment by chofski** [comment]
Here are my views:
- **Aptamer**: I prefer the first variant that I've seen used a lot.
- **Codons**: I find all of these very confusing and specific. Personally, it seems like a level below what is useful as a standard design language (and doesn't stop people annotating SBOLv designs with this information as they see fit).
- **Homology**: fine by me and would be nice to have a general symbol to highlight key areas of homology.
- **Inverter**: Have no idea what this is actually representing and would remove.
- **Non-coding RNA**: I like the squiggle with teeth is possible (I think this was discussed previously).
- **Origin of Transfer**: Prefer the circle with arrow. I find spirals difficult to draw.
All other ones I'm happy with what is proposed.

**Comment by swapnilb** [comment]
Regarding the Protein Domain glyph:
I am a little confused. 

1. I suspect that this glyph would necessarily have to be composable with CDS glyph(s), without confounding the meaning of the CDS glyph. 
2. Protein Domains, I presume, can be integrated into any protein, as per classic synbio paradigm.
3. Now, take any of the 5 out of the 6 proposed glyphs. They all have arrowheads. 
4. So if we were to represent domain X engineered into the middle of a CDS coding for protein Y, then we would have a "composite glyph" that looked like 

![image](https://user-images.githubusercontent.com/1002777/29723905-6713c39c-8994-11e7-867c-db859fa027a4.png)

where the red glyph (assume it is one of the 5 proposed above) is the engineered domain. This at best, can be a bit confusing, because of the extra arrowhead. How would a CDS encoding a fusion proteinor a  multi-CDS construct be denoted, without confounding it with Protein Domains?

FWIW, pigeon has allowed for fusion CDSes to be denoted as follows, and it has seen quite a bit of use (judging from several folks who signed up to ask for it, out of the blue):

![image](https://user-images.githubusercontent.com/1002777/29724060-185b1196-8995-11e7-8734-8eb3d567cd19.png)

**Comment by jakebeal** [comment]
@swapnilb I agree that most of the proposed glyphs for Protein Domain don't compose nicely. The two that do are:
- "User Defined" rectangle: this is effectively equivalent to your current fusion CDS model, but reuses rectangles, thus giving potential for confusion.
- chevron: this works just the same way, except that the "internal" line is bent forward rather than being straight up and down. This provides the same functionality, but removes the ambiguity.

This is why I like chevron best of the options. We could further clarify the composition as a note, saying something like "when a Protein Domain is indicated within a CDS, 'internal' boundaries use the chevron, while boundaries at the extremes of the CDS follow the convention of the CDS"

**Comment by swapnilb** [comment]
@jakebeal Agree with almost everything in your latest comment, except one point:

One problem with the chevron is that if you have overlapping domains, *not* an entirely rare use case, then  if you overlap two chevrons, you can get an unintended number of chevrons. This is because of the identical geometry of the pair of lines at the start and end of the chevron. If we could fix this, then a chevron glyph for PD could work well.

**Comment by jakebeal** [comment]
I believe we've got lots of good options for distinguishing overlapping domains. One is simply to use fills that indicate the overlap:

![f3wkr](https://user-images.githubusercontent.com/10675899/29730092-704bd8ea-89a4-11e7-9dfd-1570cf0ca210.png)

One can also do it way vertical separation, textual annotations, etc.  The preference will likely depend on the circumstance.

**Comment by swapnilb** [comment]
It is not clear: my use case is that in a drawing such as yours, domain red and domain blue overlap in the grey CDS. That is, domain blue would be codons b_i to b_j and red would be r_i to r_j, where b_i < r _i < b_j < r_j.  In this case, we would get an unintended purple chevron, as you have shown. It is not immediately clear from your picture, that the purple chevron is NOT a third PD. In fact, it is very nicely suggestive of the purple chevron *being a third PD*. This is undesirable in designing a glyph.

**Comment by jakebeal** [comment]
So spread out the hatching a bit so it's less ambiguous, or use outlines instead, or text... my point is that I find this to be solvable with the tools already at hand.

![chevronsa](https://user-images.githubusercontent.com/10675899/29733383-79c1d150-89b2-11e7-8ca2-5ed98da105d9.png)

![chevronsb](https://user-images.githubusercontent.com/10675899/29733385-7c4d02f0-89b2-11e7-916a-1f07cdbb904d.png)

![chevronsc](https://user-images.githubusercontent.com/10675899/29733388-7e54248e-89b2-11e7-8059-35f9124e7d55.png)

![chevronsd](https://user-images.githubusercontent.com/10675899/29733392-82222052-89b2-11e7-9ae7-8a6c5c3c7c56.png)

**Comment by jakebeal** [comment]
I have updated the SEP based on the current state of discussion. Here is what I am currently seeing:

Symbols with apparent consensus in favor of a specific glyph:
- Aptamer: cartoon secondary structure
- ORI-T: circle-with-arrow
- Specific Recombination Site: triangle

Symbols with apparent consensus, but multiple glyph options yet to be resolved:
- Non-Coding RNA / Transcript Region: which option, or should we consider yet another?
- Protein Domain: chevron or "User Defined" rectangle?

Symbols without a clear consensus:
- Tag: SO term problem, are we OK with the glyph?
- Homology Region: needs more voices in favor or against
- polyA Site: needs more voices in favor or against
- Non Directional Sticky End: needs more voices in favor or against

Symbols with apparent consensus against:
- Codon: high complexity, low demand
- Inverter: no clear meaning, no demand, conflict with Specific Recombination Site

**Comment by jakebeal** [comment]
@chofski With respect to ncRNA, are you thinking something like this?

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/e0712eb/Glyphs/non-coding-rna/ncrna-hover-teeth-specification.png)

**Comment by chofski** [comment]
Yes, precisely. Or slight variations on it, e.g., where the "teeth" are perpendicular to the backbone and not all parallel.

**Comment by jakebeal** [comment]
@chofski Would you be willing to say what you prefer about the "teeth" version over the "no teeth" version? Personally, I prefer the "no teeth" version because it is simpler to draw and matches the RNA symbols that I have seen in a number of scientific papers (e.g., http://www.nature.com/nbt/journal/v33/n8/abs/nbt.3301.html)

**Comment by chofski** [comment]
Yes, but it is a minor preference. I'd be happy with either to be adopted.

**Comment by jakebeal** [comment]
Thank you for the clarifications.  I've added the "teeth" version to the options under consideration, and we'll see how the conversation continues to develop.

**Comment by graik** [comment]
The issue with the protein domain suggestions so far is that they are very unlike anything that is actually informally being used in the field today. The most common symbols being used currently are:
* simple rectangle (undefined in SBOL, so presumably that's not a good symbol)
* Elipse
* rounded rectangle
I would therefore like to formally suggest the latter as the recommended symbol for protein domains:

![sep004_protein_domain_suggestion](https://user-images.githubusercontent.com/1862877/29753174-d31ebd3e-8b6b-11e7-91b0-a36cf0a52afb.png)

I would further suggest that protein features are recommended to be placed *above* (or below) the encompassing CDS symbol, possibly with an extra baseline that is symbolizing the protein.

**Comment by swapnilb** [comment]
@chofski @jakebeal I highly prefer the non-teeth version for RNA. Teeth has way too high stroke complexity.

Also, if I understand correctly, we should be careful to call it "DNA encoding ncRNA" -- in that this glyph cannot be used to depict the RNA transcribed. (Or if it can, then that should be mentioned in the spec.) I also prefer the boxed variant for ncRNA since it clearly shows it as being part of the DNA.

As to chevron -- I understand that the problem can be solved, but I don't support adding a known confusion into the spec. The overlap problem needs to be dealt with at some point, and it is best if we don't make it worse.

**Comment by swapnilb** [comment]
@graik I concur that we need to develop a standard way to describe overlapping features. I agree, the PD would be better illustrated if it could be aligned beside the CDS.

**Comment by swapnilb** [comment]
@jakebeal please note this too:

Tag: I object to the current glyph because:
- it is a rotated version of the CDS. No compelling reason it should be. 
- It is not naturally scalable in the X direction.
- Minor: cartoon price tags have a hole at the pointy end.

**Comment by jakebeal** [comment]
> Also, if I understand correctly, we should be careful to call it "DNA encoding ncRNA" -- in that this glyph cannot be used to depict the RNA transcribed.

@swapnilb I believe the associated SO term is clear: "SO:0001263: Non-Coding RNA Gene", so I've changed the glyph name in the SEP to be exactly that.

**Comment by jakebeal** [comment]
@graik I'm a bit confused by your proposal: it sounds like you're thinking this glyph is describing part of an actual protein, like in our ACS SynBio paper? That is not the case here: per the SO term, this glyph is intended to describe a portion of a CDS.

**Comment by graik** [comment]
OK, that wasn't clear for me. I thought the same symbol would end up being used for protein sequence annotation as well. If we restrict ourself to DNA only, then the perhaps basic problem is how to have both the CDS symbol and overlapping RNA or protein symbols coexist. For example, I like the "Tag" symbol but how is it going to overlay on a CDS? Inside of it? Above it? Or should there be no CDS symbol if details are shown for the ORF? 
 
Pragmatically, I think @swapnilb 's 2-way fusion CDS shown above is the most straightforward and intuitive to demarcate sub-elements in a ORF including domains.

**Comment by jakebeal** [comment]
@graik I agree that composition is a critical requirement of CDS "sub-components." We do not have a formal composition model, nor is this SEP the place to develop one (though I would encourage development of that in a new SEP).  

I thus think that for CDS-related elements, we remain at the same place: showing composition by the "fusion" method used by @swapnilb, either with straight boundaries ("User Defined") or with angled boundaries (chevron).

Furthermore, given the serious problems that Tag has with composition and SO term, and the fact that these do not seem to have any promising paths to resolution, I have moved Tag to the "consensus against" set --- we would thus recommend that protein tags be indicated with Protein Domain glyphs, which I think is reasonable.  I have also moved the ncRNA gene "squiggle with teeth" down since it had only mild support but strong opposition.

**Comment by jakebeal** [comment]
Would anybody like to speak about Homology Region, polyA site, or Non Directional Sticky End?  

If I don't hear more significant backing for these, I am going to move them to "these don't seem important enough to anybody to add at this time."

**Comment by cjmyers** [comment]
I’m not locked into a particular glyph for it, but I believe we need one for polyA, since this is common in the iGEM dataset.  Three As is fine by me, but I’m open to alternative suggestions.

**Comment by jakebeal** [comment]
Updated again based on the current state of discussion. I think we may be nearly ready to move forward for a vote. Here is what I am currently seeing:

Symbols (maybe) ready for voting:

- Aptamer: cartoon secondary structure
- ORI-T: circle-with-arrow
- Specific Recombination Site: triangle
- polyA Site: three As
- Protein Domain: vote should decide whether to adopt chevron or to leave undefined and thus defaulting back to a "User Defined" rectangle

Symbols without sufficient backing, and thus not being voted on (they may be revisited in the future): Codon, Homology Region, Inverter, Non Directional Sticky End, Tag

We still need to discuss Non-Coding RNA and Mature Transcript Region. I believe that Mature Transcript Region should be discarded, since the SO term covers specifically transcripts, and not sequences coding for functional transcripts (which is handled neatly by ncRNA). I would then propose we move forward with a vote to decide which of the two ncRNA glyphs should be retained.  

What do people think of this proposal?

**Comment by cjmyers** [comment]
ncRNA in SO (http://www.sequenceontology.org/browser/current_svn/term/SO:0000655) seems to describe an RNA and not a region of DNA that represents a non-coding RNA region.  This is why we used mature transcript region (http://www.sequenceontology.org/browser/current_svn/term/SO:0000834).  This is the parent term that includes mRNA, which includes CDS, ribosome entry site, etc.  Granted mature transcript region is too general, but if you don't know what type of non-coding RNA it codes for then there is no good parent term to use.  The solution here might be that we need to contact SO folks.

**Comment by jakebeal** [comment]
@cjmyers That is why the current proposal does not use that term. SO:0000834, in fact, has the same problem.

Instead, the current proposal uses Non-Coding RNA Gene (http://www.sequenceontology.org/browser/current_svn/term/SO:0001263), which is for a region of DNA that represents a non-coding RNA region.

**Comment by cjmyers** [comment]
Ah, did not notice that.  That is a better definition, but it makes it less parallel with CDS.  I would have expected these terms to be cousins.

**Comment by jakebeal** [comment]
I take back what I said about SO:0000834, which is fine. I was getting is confused with http://www.sequenceontology.org/browser/current_svn/term/SO:0000233 --- the parallel terminology in very differently structured parts of the ontology is frustrating to me sometimes.

I would be comfortable to have both SO:0001263 and SO:0000834 be legitimate SO terms for this. We are, in fact, allowed multiple terms, and have used it before (e.g., Ribosome Entry Site is given both SO:0000139 and SO:0000204).

**Comment by cjmyers** [comment]
I think we might want to see if we can get the SO folks to add a parent to the RNA coding regions of the DNA that are not mRNAs.  In other words a child of 834 that is a parent to all but 836.

**Comment by jakebeal** [comment]
That would still be problematic because 836 contains things like "riboswitch" and "RNA thermometer" that are functional RNA rather than protein coding RNA.

**Comment by cjmyers** [comment]
These though are still part of the mRNA to regulate its translation into a protein though?  I thought the distinction we are wanting is a glyph that indicates that the region codes for protein or does not code for protein.  My understanding is that mRNA codes for protein, and the other RNA options here do not, even if parts of the mRNA region are there only for regulation of translation.

**Comment by jakebeal** [comment]
I believe that things like riboswitches might be used to regulate other functional RNA as well, by modulating its stability. I am not certain, but certainly wouldn't count on artificial systems remaining isolated thus.

**Comment by jakebeal** [comment]
For now, I have merged the two, giving both SO terms.

**Comment by jakebeal** [comment]
Returning to the question of protein domains: I would like to remove the "rectangle" option. My reasons are:

1. It is redundant with the use of rectangle for Unspecified.  Thus, if we want "rectangle", we should just not assign a glyph.
2. At the same time, it will conflict with the use of rectangle in Composite and (likely) No Glyph Assigned

@swapnilb @graik @cjmyers Would you be OK with this?

**Comment by jakebeal** [comment]
I'd also like to pick just one of the three ncRNA options, if we can. Would people be OK with the recommended vote being: "pick one" rather than "do you like all three as alternatives"?  And can we eliminate any before voting?

**Comment by cjmyers** [comment]
I agree.

**Comment by cjmyers** [comment]
Ok with pick one.  Also okay to eliminate one.  I’m not partial to any particular one.

**Comment by jakebeal** [comment]
On ncRNA, a bit of searching around the literature online finds that the main ways of diagramming ncRNA at present are:

- "single strand wiggles"
- unspecified rectangles
- complex shape diagrams

I thus propose to remove the "peeling teeth" ncRNA from consideration, then put "wiggle" vs. "box-wiggle" to a vote, since I know that I strongly prefer "wiggle" and @swapnilb has stated that he prefers "box-wiggle".

**Comment by cjmyers** [comment]
Sounds good to me.

**Comment by swapnilb** [comment]
I strongly prefer "box-wiggle." To reiterate: this is the DNA encoding some ncRNA. So I like that it is attached to the backbone and NOT hovering.

I think we should punt on protein domains. It requires more careful design. So I am OK with removing the rectangle option at the very least.

For the protein domain chevron, I am still NOT OK with it. It's known to not be, and by design, is not a good glyph. Therefore, I propose that we have another symbol such that none of its X-directional overlapping translations forms an unintended glyph. Any glyph that smoothly varies in the X/-X direction would do the job, and would improve the visualization of overlapping domains, which is likely a common use case.

**Comment by jakebeal** [comment]
@cjmyers Do you have any problem with deferring on protein domain for now? I think @swapnilb makes a good case for deferring, and I would be OK with doing so --- I don't think it's a burning need, and in the mean time we can still use rectangles.

**Comment by cjmyers** [comment]
The iGEM dataset does have protein domains, so it would be nice to get this resolved.  Also, I would be against reverting to rectangle assuming the new No Assigned Glyph passes.  It should shift to "[ protein domain ]” instead.

@swapnil can you put forth a concrete alternative for protein domain that satisfies your concerns?

**Comment by jakebeal** [comment]
I made a couple of other variants of the "wiggle-box" ncRNA that have what I find to be a prettier wiggle.  They're not actually intended to be different alternative glyphs, just different stylings in search of one that best presents the "wiggle-box" option.  Here are the three current stylings:

![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/4a72280/Glyphs/non-coding-rna/ncrna-boxB-specification.png)
![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/0cac2206/Glyphs/non-coding-rna/ncrna-boxC-specification.png)
![glyph specification](https://raw.githubusercontent.com/SynBioDex/SBOLv-realizations/0cac2206/Glyphs/non-coding-rna/ncrna-box-specification.png)

@swapnilb Which of these stylings do you like the best?

**Comment by swapnilb** [comment]
I don't have a preference among these, because I consider them in the same equivalence class. Indeed, I think we should allow any reasonable "wiggle," including a pointy "resistor" style wiggle.

(Side note: If we are pedantic about glyph elements, we may turn away people without very precise drawing skills. We should design for everyone. So our glyphs need to have a good "noise margin" around them. I consider the wiggle type to fall in that margin.)

**Comment by jakebeal** [comment]
@swapnilb OK, I'm picking the one I find "prettiest," and we'll see which way the votes go.  I *do* think that "sawtooth" is different from "wiggle" --- or at least it certainly will be if we end up choosing that option on SEP V007.

I've also moved "protein domain" into the "not moving forward" section for now.  They'll end up getting rendered as No Glyph Assigned (per outcome of SEP V006) unless a better suggestion gets made and adopted.

**Comment by swapnilb** [comment]
OK -- though we should reconsider accepting glyphs within a very small edit distance from another glyph -- wiggle and saw tooth are a good example.

**Comment by jakebeal** [comment]
Understood.  It may be worth noting that the difference is quite similar to inductor vs. resistor in electronic symbols --- whether that argues for or against, though, is a matter of opinion.

**Comment by bbartley** [comment]
Just a quick observation.  Homology region DOES have an associated SO term, sort of:  "homologous_to"

**Comment by jakebeal** [comment]
@bbartley SO reference?

**Comment by bbartley** [comment]
Rather than homologous_to (which is in the Relationship branch of SO), there is also SO:0000853 (homologous_region) which is a child of SO:0000857 (homologous).  These latter are probably more appropriate terms.

See http://www.sequenceontology.org/browser/current_svn/term/SO:0000853

**Comment by jakebeal** [comment]
Great: marked it with SO:0000853, for future reference.

**Comment by jakebeal** [comment]
Accepted and integrated, and thus closed per SBOL procedure in updated SEP 001.
