### ISSUE TITLE
Interaction specs are missing their Participations

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#83]
SBOL Visual 2.1 supports Interactions, for which the head and tail imply SBO roles in a Participation. All of the actual glyph specifications, however, omit the head and tail roles.

I do not believe this requires an SEP, because participations are in the spec, and for each glyph the associated relations are all already defined in the SBOL data specification.

When this is completed, the ontology will need to be updated to include them as well.

**Comment by jakebeal** [comment]
Fix pending in #85

**Comment by goksel** [comment]
The pull request for this change has been merged into the develop branch.
