### ISSUE TITLE
Ontology needs Participations for interactions

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#88]
Now that #83 has been resolved, the ontology needs to be updated to include participations as well.

**Comment by goksel** [comment]
@jakebeal I incorporated new terms to the ontology: hasTail, hasHead, hasIncoming and has Outgoing. These properties link glyph terms to SBOL terms through sbol2.role property.

**Comment by jakebeal** [comment]
Where is this commit? I don't see it in #106 and am not seeing it on any other branch either.

**Comment by goksel** [comment]
@jakebeal Please close the issue after your merge the pull request https://github.com/SynBioDex/SBOL-visual/pull/133
