### ISSUE TITLE
Glyph should have subclasses for the four main types

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOL-visual#96]
If one wants to programmatically browse through glyphs, it's useful to be able to separate out the sequence feature glyphs from the molecular species from the interactions and interaction nodes.

As such, we should have subclasses for the four main types of glyph, rather than putting them all together under Glyph.

**Comment by goksel** [comment]
@jakebeal, I added the four main glyph categories and made a pull request for issue 96. I hope the changes are ok. Please let me know if you are require any changes.

**Comment by goksel** [comment]
I also added instructions below regarding how to update the ontology and the HTML version:
https://dissys.github.io/sbol-visual-ontology

**Comment by jakebeal** [comment]
Where is that hosted from?  I still see the old instructions in the SBOL
Visual repository:
https://github.com/SynBioDex/SBOL-visual/tree/master/Ontology

**Comment by goksel** [comment]
@jakebeal, instructions about how to update the ontology is here: https://dissys.github.io/sbol-visual-ontology

**Comment by jakebeal** [comment]
Right, but I think that it would be a good idea for this all to migrate into community repositories and community websites if it's going to be a long-term community resource.  I'll open an issue for this, and hopefully we can sort it out as part of the workflows discussion at COMBINE.

**Comment by goksel** [comment]
@jakebeal  I suggest closing this issue after I move the ontology to SynBioDex.

**Comment by jakebeal** [comment]
@goksel We also need the pull request addressing this issue (#106) to be able to be resolved, which needs SBO restrictions to get put back on Interactions again. That's what it's been waiting for.

**Comment by goksel** [comment]
@jakebeal Please close the issue after your merge the pull request https://github.com/SynBioDex/SBOL-visual/pull/133
